### ISSUE TITLE
Regen gtk 4 libs

### ISSUE THREAD

**Issue by GuillaumeGomez** [gtk-rs/sys#153]
Can be done once https://gitlab.gnome.org/GNOME/gtk/issues/2230 is fixed.

**Comment by sdroege** [comment]
There was a new GTK4 release, so it's probably about time to try again and report what else is missing now :)

**Comment by sdroege** [comment]
Newly blocked by https://gitlab.gnome.org/GNOME/gtk/issues/2454

**Comment by bilelmoussaoui** [comment]
This can be closed I guess
