### ISSUE TITLE
SocketFamily::Ipv6 definition is wrong because it's OS dependent

### ISSUE THREAD

**Issue by xanathar** [gtk-rs/sys#178]
This issue involves many repos (sys, gio, and gir-files), so I'm not 100% sure this is the correct one to open the issue to. I've tried to solve the issue, but could not find a similar case to copy so, in case, guidance is needed.

TL;DR: The value of the constant `gio_sys::G_SOCKET_FAMILY_IPV6` is operating system dependent, and so code using it (directly or indirectly) fails on non-Linux OSs (Linux is safe because gir files are generated from Ubuntu's .debs).

### Repro/Symptom

Running a simple code like:

```
    if let Err(e) = Socket::new(SocketFamily::Ipv6, SocketType::Datagram, SocketProtocol::Udp) {
        println!("ERROR: {:?}", e);
    }
```

fails on MacOS (and Windows) with the following output:

```
(process:7858): GLib-GObject-WARNING **: 20:12:12.881: value "((GSocketFamily) 10)" of type 'GSocketFamily' is invalid or out of range for property 'family' of type 'GSocketFamily'
ERROR: Error { domain: g-io-error-quark, code: 13, message: "Unable to create socket: Unknown family was specified" }
```

on the other hand the following works (on MacOS):

```
    if let Err(e) = Socket::new(SocketFamily::__Unknown(30), SocketType::Datagram, SocketProtocol::Udp) {
        println!("ERROR: {:?}", e);
    }
```

### Root cause

- `SocketFamily::Ipv6` is defined to be the same value (via the `to_glib` method) of `gio_sys::G_SOCKET_FAMILY_IPV6`
- `gio_sys::G_SOCKET_FAMILY_IPV6` has a fixed value of `10` in https://github.com/gtk-rs/gir-files/blob/master/Gio-2.0.gir
- The value in Gio-2.0.gir comes from a `libgirepository1.0.*.deb` package of Ubuntu and the original glib sources.
- Checking the original glib sources, the constant is defined in `glib/glibconfig.h.in` as a constant coming from meson
- Checking `meson.build` it seems that it takes the value from the `AF_INET6` constant from system includes
- `AF_INET6` is defined as `10` on Linux (at least, Ubuntu), as `30` on MacOS and as `23` on Windows (found by inspecting system SDK header files)

**Comment by sdroege** [comment]
This means that we should ignore these constants from the .gir file and instead point at `libc::AF_INET` etc. manually.

We already do similar things in https://github.com/gtk-rs/sys/blob/master/glib-sys/src/manual.rs for example.

Do you want to provide a PR for this?

**Comment by xanathar** [comment]
Sure! I just needed this pointer :)

**Comment by sdroege** [comment]
Ignoring can be done via the `Gir.toml` file btw :)
