### ISSUE TITLE
g_key_file_load_from_data_dirs arg 2 should be *const

### ISSUE THREAD

**Issue by hfiguiere** [gtk-rs/sys#29]
g_key_file_load_from_data_dirs arg 2 should be *const. It is currently generated as *mut

For refrence, the C prototype is
````C
gboolean g_key_file_load_from_data_dirs (GKeyFile *key_file,
                                const gchar *file,
                                gchar **full_path,
                                GKeyFileFlags flags,
                                GError **error);
````

**Comment by EPashkin** [comment]
Problem in source GLib-2.0.gir which is not your.
```xml
<parameter name="file" transfer-ownership="none">
  <doc xml:space="preserve">a relative path to a filename to open and parse</doc>
  <type name="filename" c:type="gchar*"/>
</parameter>
```
But it seems don't effect on generated code (with  `g_key_file_load_from_file` as example)
```rust
    pub fn load_from_file<T: AsRef<std::path::Path>>(&self, file: T, flags: glib::KeyFileFlags) -> Result<(), Error> {
        unsafe {
            let mut error = ptr::null_mut();
            let _ = ffi::g_key_file_load_from_file(self.to_glib_none().0, file.as_ref().to_glib_none().0, flags.to_glib(), &mut error);
            if error.is_null() { Ok(()) } else { Err(from_glib_full(error)) }
        }
    }
```

**Comment by hfiguiere** [comment]
I don't even see these wrappers in the repository. I'd just use that. See gtk-rs/glib#135

**Comment by EPashkin** [comment]
Its from my attempt to generate `GKeyFile` from your issue.

**Comment by hfiguiere** [comment]
ah ok. I see. Thanks !

**Comment by gkoz** [comment]
Anyway passing a string requires ([copying it into a temporary `CString`](https://github.com/gtk-rs/glib/blob/9f77b36524b9bfb5196cba48fc25314cd5345664/src/translate.rs#L342-L345)) so generally this kind of discrepancy should not be a problem.
