### ISSUE TITLE
g_main_loop_new accepts NULL

### ISSUE THREAD

**Issue by aeosynth** [gtk-rs/sys#30]
https://developer.gnome.org/glib/stable/glib-The-Main-Event-Loop.html#g-main-loop-new

> context a GMainContext (if NULL, the default context will be used).

i'm still new to rust, but would it be possible to use `std::ptr::null` as the context for `g_main_loop_new`?

edit: or make context an `Option`, so i can pass `None`

**Comment by gkoz** [comment]
You've got the right idea with `ptr::null()` it's just the function wants a mutable pointer so you need `ptr::null_mut()` to make the compiler happy.
