### ISSUE TITLE
Expose Object structures so we can subclass them

### ISSUE THREAD

**Issue by thiblahute** [gtk-rs/sys#34]
To be able to subclass GObject, the exposed GObject structure need to have the right size, so also include the private fields. It is the case with basically any class but I hit the problem trying to [create a GObject subclass](https://github.com/thiblahute/rust-gobj-exp/blob/master/rust-gobject/src/main.rs)

Basically with that stupid patch it works:

``` diff
diff --git a/gobject-sys/src/lib.rs b/gobject-sys/src/lib.rs
index b3bc4e1..51f4af4 100644
--- a/gobject-sys/src/lib.rs
+++ b/gobject-sys/src/lib.rs
@@ -438,7 +438,12 @@ pub struct GBinding(c_void);
 #[repr(C)]
 pub struct GInitiallyUnowned(c_void);
 #[repr(C)]
-pub struct GObject(c_void);
+pub struct GObject {
+    pub g_type_instance: GTypeInstance,
+    ref_count: c_uint,
+    qdata: *mut glib::GData,
+
+}
```

I know everything is generated, but I can't build ( as I am getting ```rustc: /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/llvm/lib/IR/Instructions.cpp:1304: void llvm::StoreInst::AssertOK(): Assertion `getOperand(0)->getType() == cast<PointerType>(getOperand(1)->getType())->getElementType() && "Ptr must be a pointer to Val type!"' failed.``` while compiling `git2` ) thus I can't really play with it right now.

I will try to make some time to do it the right way but I would like to first have you opinion about it and maybe get some pointers about how that should happen.

**Comment by EPashkin** [comment]
Possible related PR: https://github.com/gtk-rs/gir/pull/276

**Comment by EPashkin** [comment]
It generated
```
#[repr(C)]
pub struct GObject {
    pub g_type_instance: GTypeInstance,
    ref_count: Volatile<c_uint>,
    qdata: *mut glib::GData,
}
```
But it also can be bad as we have https://github.com/gtk-rs/sys/issues/25 (it's old issue and I don't understand it)

**Comment by thiblahute** [comment]
> Possible related PR: gtk-rs/gir#276

Yes that sounds very  related, looks like it is quite ready to merge isn't it?

**Comment by thiblahute** [comment]
> But it also can be bad as we have #25 (it's old issue and I don't understand it)

Well, at least for all derivable GObject you will need to expose the class structures otherwise it will not be possible to subclass.

**Comment by EPashkin** [comment]
@thiblahute, subclassing from `GObject` in https://github.com/gtk-rs/sys/issues/34#issuecomment-265565086 is work's despite it have private fields?

**Comment by thiblahute** [comment]
> @thiblahute, subclassing from GObject in #34 (comment) is work's despite it have private fields?
@EPashkin With that definition it does work yes.

(not sure what was the question tbh :))

**Comment by EPashkin** [comment]
@thiblahute we have option to make all fields in classes structs public, but if it not really needed IMHO better don't do that.

**Comment by thiblahute** [comment]
> @thiblahute we have option to make all fields in classes structs public, but if it not really needed IMHO better don't do that.

Well, if you are using GObject you probably want to subclass objects, and in that case you need to have access to the actual Object structure, thing is that in GObject land we usually put private fields after a ```/*< private >*/``` delimiter, those fields should ideally be all private.

My goal is to write GStreamer elements in pure rust, so I will need to be able to subclass :)
