### ISSUE TITLE
cannot build on windows

### ISSUE THREAD

**Issue by phisk** [gtk-rs/sys#73]
Hi there :)

Building on windows https://github.com/antoyo/relm/blob/master/examples/clock.rs fails with following error:

```
Compiling futures-glib v0.3.1
error[E0423]: expected value, found module `ptr`
  --> C:\Users\p\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-glib-0.3.1\src\io\mod.rs:41:18
   |
41 |         assert!(!ptr.is_null());
   |                  ^^^----------
   |                  |
   |                  did you mean `ptr::is_null(...)`?

error[E0423]: expected value, found module `ptr`
  --> C:\Users\p\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-glib-0.3.1\src\io\mod.rs:43:20
   |
43 |             inner: ptr,
   |                    ^^^ not a value

error: aborting due to 2 previous errors

error: Could not compile `futures-glib`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

Building the same on linux works fine

**Comment by EPashkin** [comment]
@phisk Seems you filled error on wrong place.
This code https://github.com/antoyo/futures-glib-rs/blob/master/src/io/mod.rs#L37-L45 uses `ptr` variable without defining it.

**Comment by EPashkin** [comment]
cc @antoyo just in case

**Comment by phisk** [comment]
> This code https://github.com/antoyo/futures-glib-rs/blob/master/src/io/mod.rs#L37-L45 uses ptr variable without defining it.

Thank you for guiding me there

Opened an issue over there :)

https://github.com/antoyo/futures-glib-rs/issues/10

**Comment by EPashkin** [comment]
@phisk  Don't forget close this issue 😉
